
name: Build and Push
on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

env: 
  Dockerfile_Backend: Dockerfile
  Dockerfile_Web: web/Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0 

      - name: Setup AWS Creds 
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-west-2
